#! /bin/bash
#SBATCH -A see200002p
#SBATCH -p GPU-shared
#SBATCH --gpus=v100-32:1
#SBATCH -J myjob
#SBATCH --mail-user=oscarwyx@udel.edu
#SBATCH --mail-type=ALL
#SBATCH -N 1
#SBATCH -n 4
#SBATCH -t 00:05:00

nvc -acc -ta=tesla -Minfo=accel mandel.c -o mandel_yongxu
./mandel_yongxu
